### ISSUE TITLE
Consider the definition of one source of truth for CoC, DCO, Contrib...

### ISSUE THREAD

**Issue by dpordomingo** [src-d/guide#121]
We currently copy the content of:
- [CODE_OF_CONDUCT](https://github.com/src-d/guide/blob/master/.github/CODE_OF_CONDUCT.md)
- [DCO](https://github.com/src-d/guide/blob/master/engineering/documents/DCO)
- the first five sections of the [CONTRIBUTING](https://github.com/src-d/guide/blob/master/engineering/documents/CONTRIBUTING.md)

Would it be useful to link to that files in src-d repositories instead of copying its contents?

About the `CONTRIBUTING.md`, since each project is different to the others, there can be special requirements (like the `development` section). If/when it happens, the project `CONTRIBUTING.md` would contain the link to the company one, plus the local differences.

If we do so:
- the maintenance of those files will be easier,
- it will be ensured that all our repos follow the same rules,
- it will be easier for us to know (and validate) what differences do we require for certain projects.

**Comment by dpordomingo** [comment]
Here is an example of how [Twitter reuse its CoC](https://github.com/twitter/twitter-kit-ios#code-of-conduct), pointing to [its main CoC](https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md)

**Comment by dpordomingo** [comment]
Ouch, sorry for forgetting this!
Yes, all your three proposals make sense to me and would solve the problems I described.
Ping me if you need assistance with the projects I maintain.

**Comment by campoy** [comment]
I sent a new PR #184, let me know what you think
