### ISSUE TITLE
Define the offboarding process

### ISSUE THREAD

**Issue by dpordomingo** [src-d/guide#122]
There are people that assert that:
> _A great offboarding experience can also woo stellar “boomerang employees” to come back in the future or recommend the company to their qualified friends and family._

Do you think it could be a good idea to define the process or try to explain it?

Random [example with rationale and checklist](https://www.softwareadvice.com/resources/employee-offboarding-checklist/)

**Comment by eiso** [comment]
@dpordomingo this is an excellent idea, we have a process already but it's not documented. 

@tsolakoua could you add this to your backlog.

**Comment by tsolakoua** [comment]
@eiso, done.

**Comment by eiso** [comment]
Where is the PR that implements this?

**Comment by tsolakoua** [comment]
The "Done" was referring to your comment to add this to my backlog. I've already started working on that and will have the first PR in a couple of days :)

**Comment by estherrgarcia** [comment]
I just saw this. I really need to learn more about github :woman_facepalming: Sorry Anna

I prepared something like than a few months ago. I didn't know that we wanted to add it here, so we should change the format, and i guess add some missing information (regarding the ESOP, for example). But maybe it's helpful to start @tsolakoua 
We can rewrite it together if you want ;)

https://docs.google.com/document/d/1ZK-JulPOgU4kSzZKEVEr7GMPYiMaGfGLPiGViAU3kQM/edit?usp=sharing

**Comment by eiso** [comment]
@tsolakoua why don't you do a GitHub QnA session with Esther; share the knowledge

**Comment by tsolakoua** [comment]
The document @estherrgarcia has prepared is great with specific necessary information (comparing to the one what I had started writing that was very general). It would be nice to work on the existing document together!

**Comment by eiso** [comment]
https://github.com/src-d/guide/pull/147
