### ISSUE TITLE
Clarify the vacations during weekends and holidays

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/guide#13]
It is possible to take a vacation which intersects with holidays or weekends. In Russia, they count it as a part of your vacation and not adjust the vacation factual length (but you've got 28 days). I am not sure how it is in Spain: are they included or discarded?

**Comment by jorgeschnura** [comment]
Here they don't count as part of them, so it's a better policy. I'll clarify it!

**Comment by jorgeschnura** [comment]
Is it clear as it is now? I updated it

**Comment by jorgeschnura** [comment]
ping @vmarkovtsev

**Comment by vmarkovtsev** [comment]
Yep, thank you!
