### ISSUE TITLE
DD template is not attached to the workflow

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/guide#145]
Design document template is not linked here: https://github.com/src-d/guide/blob/master/engineering/workflow.md#design-document-1st-iteration

**Comment by eiso** [comment]
@marnovo you can link it to here: https://github.com/src-d/guide/blob/master/product/design-documents.md

**Comment by eiso** [comment]
@marnovo ping

**Comment by marnovo** [comment]
PR open at #182.
