### ISSUE TITLE
Esther needs info about how to proceed with "family/friends stay" reimbursements

### ISSUE THREAD

**Issue by juanjux** [src-d/guide#217]
From: https://github.com/src-d/guide/blob/fe18e8d07939d8751fd237ab56fbe096cfe0e7fc/general/expenses_travel.md#what-expenses-are-covered-when-travelling

I asked @estherrgarcia  about this because of this week because I'll be staying at my beach house during Jon The Beach 2018 but she said it has never been done before so she doesn't know how to proceed.

cc @jorgeschnura

**Comment by eiso** [comment]
> we will pay you 50% of what your lodging would've cost!

@estherrgarcia pay @juanjux a bonus in his salary of 50% of what it costs for other teammates for whom we're booking lodging
