### ISSUE TITLE
DCO: should source{d} employees sign-off?

### ISSUE THREAD

**Issue by smola** [src-d/guide#221]
As per discussion here https://github.com/src-d/conferences/pull/63 it seems source{d} employees do not need to sign-off.

If that is the case, we would need to:
* update both our DCO checker for PRs (which, I guess, would require everyone either signing-off or committing with the corporate email)
* update the guide https://github.com/src-d/guide/blob/956c0d0d240abc8e5dd37df9fdb8bb8ce34768fe/engineering/licensing.md#developer-certificate-of-origin since it currently says:

> All our projects should include a Developer Certificate of Origin (DCO) document to protect us against any individual contributor revoking our rights to distribute their contribution to any of our projects.

> In practice, this means that every commit since the introduction of the DCO, should be signed off by the author, using git commit -s. **Being irrelevant if the author is a source{d} employee or an individual contributor.**

@eiso @mcuadros

**Comment by campoy** [comment]
Rather than asking people to use their corporate email, could we instead have a list of the authorized emails?

Two reasons for this:
- it's easy to forge a fake blahblah@sourced.tech email and get the DCO bot to think it's fine
- I've been using campoy@golang.org for most of my OSS work and I'd rather keep it that way (having two identities on git is a pain)

**Comment by smola** [comment]
@campoy Actually we cannot prevent the forgery with email checking, but we could check GitHub accounts that created a PR and check if they are members of the `src-d` organization.

I would suggesty that, even if we add some kind of whitelisting, you can continue using whatever email and account you want if you sign-off your commits.

**Comment by smola** [comment]
Also, checking at PR level instead of commit-level has an interesting edge case: if I cherry-pick a 3rd party commit that is not signed-off and create the PR myself, it would pass the whitelist, but it would not be legally valid. So proper whitelisting should probably check both PR account + emails in all commits.

**Comment by jfontan** [comment]
The checker can be configured to bypass sign check for organization members. I'm not sure how it is enforced.

https://github.com/probot/dco#skipping-sign-off-for-organization-members

**Comment by dpordomingo** [comment]
email and signoff message can be imposted
commits can be GPG signed (`--gpg-sign`) so it could be used to ensure they where made by sourcerers

**Comment by smola** [comment]
@dpordomingo But Pulll Request account taken from GitHub API cannot.
It would be cool that we all used `--gpg-sign`, but dropping the requirement of signing-off just to add the requirement of GPG-signing is going to add more friction instead of removing it.

**Comment by eiso** [comment]
AFAIK employees don't have to sign-off but it makes it easier as people go on to other companies, to just have it be the habit.

**Comment by smola** [comment]
Note that you can also setup a client-side hook to add sign-off to all your commits to a given repository: https://stackoverflow.com/a/46536244

**Comment by smola** [comment]
Maybe this is a non-problem. By now everyone at source{d} should be used to to add `-s` to all commits or have configured their local repositories to sign-off everything by default.
