### ISSUE TITLE
DCO: is sign-off required for trivial changes (e.g. typo in README)?

### ISSUE THREAD

**Issue by smola** [src-d/guide#224]
Should we merge trivial changes such as a fixed typo in README without sign-off?

See practical example: https://github.com/src-d/gitbase/pull/292#issuecomment-391339160

cc @eiso

**Comment by smola** [comment]
I think this is a good example of change not subject to copyright?

https://github.com/src-d/gitbase/pull/277

Typo fix: just removing a word, not modifying or adding any content.

**Comment by smola** [comment]
Note that the FSF talks about _[legally significant changes for copyright purposes](https://www.gnu.org/prep/maintain/maintain.html#Legally-Significant)_.

However, this is a highly subjective concept:

> A change of just a few lines (less than 15 or so) is not legally significant for copyright. A regular series of repeated changes, such as renaming a symbol, is not legally significant even if the symbol has to be renamed in many places. Keep in mind, however, that a series of minor changes by the same person can add up to a significant contribution. What counts is the total contribution of the person; it is irrelevant which parts of it were contributed when.

I would rather not put the responsibility on source{d} developers to asses this on their own.

**Comment by eiso** [comment]
What @smola mentions is correct. If you ever need feedback before replying to a developer, feel free to ping @jorgeschnura or myself.

**Comment by smola** [comment]
@eiso Do you mean that we can accept typo fixes without the DCO?

**Comment by eiso** [comment]
Correct

**Comment by smola** [comment]
Thanks @eiso!
