### ISSUE TITLE
Available hardware: a keyboard with silent switches

### ISSUE THREAD

**Issue by bzz** [src-d/guide#226]
source{d} office in Madrid is awesome open space, but on the pick of productivity it also may become a little bit noisy, and the list of available hardware does not include any _silent keyboard_ option ⌨️ 

I would like to know if anybody else, for the sake of sanity of your colleagues, would be interested to fix it, if an option is provided for those honorable souls who feel empathy for their co-workers: by choosing the same keyboard, but with **Cherry MX Red _Silent_ Switches**.

🙏 🙏 🙏  

It would be really great if we could allow for a option of exactly the same keyboard **Fnatic Gear Rush** [that we already have](https://github.com/src-d/guide/blob/master/general/available_hardware.md#keyboards) but with _Cherry MX Silent switches_ - [Amazon.es](https://www.amazon.es/profesional-videojuegos-Fnatic-Rush-Silent/dp/B06VT1VL81/ref=sr_1_2?ie=UTF8&qid=1528471122&sr=8-2&keywords=Fnatic%2BGear%2BSilent&th=1), [official web-site](https://shop.fnatic.com/products/rush-pro-gaming-keyboard-silent-red-mx-cherry-switches)

It's exactly the same, but would allow your [may-be-misophonic](https://en.wikipedia.org/wiki/Misophonia) colleagues to stay calm and more relaxed, while working from our spacious office in the center of Madrid.

<details>

[<img width="600" alt="screen shot 2018-06-08 at 5 42 59 pm" src="https://user-images.githubusercontent.com/5582506/41167529-71f0e592-6b43-11e8-84d4-43d5563a7477.png">](https://soundcloud.com/tylerwilde-1/cherry-mx-red-switches-vs-cherry-mx-silent-switches)

<details />

**Comment by smola** [comment]
It makes a lot of sense to add that option.
Although I think that a lot of us are already using the Blue and Brown switches and contributing to the clicks from hell noise...

**Comment by gomesfernanda** [comment]
I believe it makes complete sense, thanks Alex!

**Comment by marnovo** [comment]
> I would like to know if anybody else, for the sake of sanity of your colleagues, would be interested to fix it, if an option is provided for those honorable souls who feel empathy for their co-workers: by choosing the same keyboard, but with Cherry MX Red Silent Switches.

Been there; seen it; done that!

For those willing to try Cherry MX Silent Red Switches on how they feel and sound, my Varmilo keyboard is available on my desk. Just keep greasy fingers and liquids away, please.

**Comment by smola** [comment]
@bzz I think you might want to create a PR right away adding the model you're proposing and adding it as the first option in the list.

**Comment by bzz** [comment]
@smola proposed in #296
