### ISSUE TITLE
By Devs Training – Add learn enough Git & CLI to be dangerous to resources

### ISSUE THREAD

**Issue by marnovo** [src-d/guide#24]
Two really great resources for learning command line and git. Very well explained and ramp up in complexity well.

Might event be "core-quest" material, if not at least a must-be for the "DLC". Let me know your opinions on them.

- CLI: https://www.learnenough.com/command-line-tutorial
- Git: https://www.learnenough.com/git-tutorial

**Comment by jorgeschnura** [comment]
Since it's full books I'll add them to the DLC. For the record, we might make parts of the DLC a part of the main quest if we see that we want to make the whole "storyline" more extensive
