### ISSUE TITLE
Org chart is out of date

### ISSUE THREAD

**Issue by rporres** [src-d/guide#374]
@glimow has left, @kuba-- is now in LA team, @agarciamontoro is in DP team

**Comment by kuba--** [comment]
I'd add that Marvin's first and last name are in wrong order..

**Comment by gomesfernanda** [comment]
Org chart updated and waiting approval to merge: https://github.com/src-d/guide/pull/377

**Comment by gomesfernanda** [comment]
https://github.com/src-d/guide/pull/377 merged
