### ISSUE TITLE
Semantic Linefeeds proposal

### ISSUE THREAD

**Issue by alcortesm** [src-d/guide#39]
I propose that we start using Semantic Linefeeds in this repository. See [1] to know why.

![xkcd - third way](https://imgs.xkcd.com/comics/third_way.png)

[1] http://rhodesmill.org/brandon/2012/one-sentence-per-line/

**Comment by alcortesm** [comment]
For instance, these two markdowns are rendered the same, but from the point of view of CVS the second one is much better:

No semantic linefeeds example:
```
This is the first sentence of the paragraph.  This is the second sentence.
```

The same rendered result, but using semantic linefeeds:
```
This is the first sentence of the paragraph.
This is the second sentence.
```

**Comment by eiso** [comment]
@alcortesm it sounds like a good idea, all though in your example it renders differently. This works on markdown files in GitHub?

If it works, is there anything out there that automatically can format all existing .md's to semantic linefeeds?

**Comment by alcortesm** [comment]
You are right, Github is not rendering Markdown correctly in PR comments.  On the other hand Gists are rendered correctly: https://gist.github.com/alcortesm/008cad4e9e80cfb7d507fd2bf8058407.

I don't know right now how Github renders markdown files in repositories, though, which is the important thing if we want people to read this guide by browsing Github.  I will find it out in the following days and come back here to close the issue or to link some examples of correctly rendered markdown.

**Comment by alcortesm** [comment]
I can confirm that Github renders markdown files written using semantic linefeeds correctly.  See https://github.com/alcortesm/demo-markdown/blob/master/afile.md as proof.

This means it is safe to adopt this proposal.

**Comment by alcortesm** [comment]
I don't know of any library to do this, but a sed or awk one-liner is probably enough.

**Comment by alcortesm** [comment]
Here is one: https://github.com/cllns/semantic_linefeeds

**Comment by eiso** [comment]
Great! I'll keep the issue open until it's properly implemented and documented. 

/cc @jorgeschnura we need another LGTM for this. Do you agree on the proposal?

**Comment by jorgeschnura** [comment]
Yes, makes sense!

**Comment by smola** [comment]
Sounds like a good idea, at least it's much more diff-friendly.
Although it might be a bit surprising for people reading source code.

**Comment by smola** [comment]
Note that, however, diffs like GitHub's are quite good at highlighting the actual parts of the lines that changed.

**Comment by vmarkovtsev** [comment]
These semantic linefeeds is a well-known lifehack to write text files. I am to it 100%.

**Comment by juanjux** [comment]
I'll have to configure my Vim to don't auto-justify Markdown files to some length with linebreaks  and I generally don't like seeing lines too long on the source (be it either source code or markdown text) which could happen with this and long sentences but if it's better for CVSs I'm fine with it.

**Comment by alcortesm** [comment]
@juanjux 
```
; cat ~/.vim/after/ftplugin/markdown.vim 
set expandtab
set tabstop=8
set shiftwidth=2

set textwidth=0
set wrapmargin=0

set formatoptions=n
set formatlistpat=^\\s*\\d\\+\\.\\s\\+\\\|^\\s*[-*+]\\s\\+
```

You are right, lines too long are ugly and should be avoided, in general, not only when using semantic linefeeds.  Let's avoid this problem by writing short sentences.

**Comment by juanjux** [comment]
Ok. But your sentence 112 chars long is. Ugly on text editor will look.

<img src="http://vignette2.wikia.nocookie.net/starwars/images/d/d6/Yoda_SWSB.png/revision/latest?cb=20150206140125" width=200px>

**Comment by alcortesm** [comment]
Try visually wrapping your long lines: http://vim.wikia.com/wiki/Word_wrap_without_line_breaks

I don't need it because I keep most of my lines sort, which I think is a better solution.

**Comment by mcuadros** [comment]
Adding another constraint to the guide, just make more tedious make the PRs. The markdown is made for be rendered so for me meanwhile can be read properly as Markdown, I don't see why we should enforce to the people have custom configuration on his editors.

**Comment by vmarkovtsev** [comment]
@mcuadros I don't see how it makes PRs more tedious. The idea is very useful and you just need to learn a little and adapt to it. It is very easy to adapt - just put every sentence on new line. Personally, I am not changing my editor configs, just writing everything properly from scratch.

```
Hints for Preparing Documents

Most documents go through several versions (always more than you expected) before they are finally finished. Accordingly, you should do whatever possible to make the job of changing them easy.

First, when you do the purely mechanical operations of typing, type so subsequent editing will be easy. Start each sentence on a new line. Make lines short, and break lines at natural places, such as after commas and semicolons, rather than randomly. Since most people change documents by rewriting phrases and adding, deleting and rearranging sentences, these precautions simplify any editing you have to do later.

— Brian W. Kernighan, 1974
```

**Comment by mcuadros** [comment]
@vmarkovtsev when you have longs likes, you need to wrap it (in my case I have word wrap after 100, so I don't need to change).
I don't find natural write every phrase in a new line.
This is not how you write normally.

**Comment by vmarkovtsev** [comment]
Sorry, I couldn't stop myself :laughing: 

![](https://www.mememaker.net/static/images/memes/4824973.jpg)

**Comment by vmarkovtsev** [comment]
Additional discussions on the topic:

https://news.ycombinator.com/item?id=4642395

https://groups.google.com/forum/#!topic/pandoc-discuss/tEWDWL2mLBY

Let's weight all the procs and cons.

**Comment by juanjux** [comment]
You could argue that there are already perfectly valid semantic end of line indicators like the dot stop. Line feeds like its name imply are not semantic but visual adjustments.

**Comment by mcuadros** [comment]
Pro:
- The diff is more clear.

Cons:
- Makes more hard format your final document. Since the sourced and the output paragraph organization is complete different. 

- Your are relaying in something that is not in the spec and even unified in GitHub, so maybe tomorrow change as you have a bunch of documents broken, like happened a few months ago with `#Foo` over `# Foo`.

- Adds another thing to worry to make a PR, also adds more work to do from the PR reviewers, and the worth a back and forth about if the line is too long or not.

**Comment by vmarkovtsev** [comment]
Regarding more clear diffs, having short lines may actually improve readability for small edits (add an article, fix punctuation, change a single word). This depends on how smart is your diff viewer though, I think GitHub highlights such cases properly.

I am starting to change my mind :) Any other pros?

**Comment by juanjux** [comment]
The last point of @mcuadros is important because as we grow we will need to avoid as much friction as possible in the PR process to avoid expending too much time reviewing them.

**Comment by jorgeschnura** [comment]
I see now more sense in @mcuadros arguments actually, not sure it is worth it

**Comment by alcortesm** [comment]
Personally, I think the cons pointed by @mcuadros are not valid:

> 1. Makes more hard format your final document. Since the sourced and the output paragraph organization is complete different.

It doesn't make formatting harder, as you don't format text when writing Markdown, that is the whole point of non-WYSIWYS typesetting systems.  Having different source than output is whole point here.

Documentation should not necessarily be easy to write, but it must be easy to read.  Just like code.  Having said that, I don't think this make writing documentation harder, it forces you to focus on the content, which I think is a good thing.

Also, it actually makes it easier to edit, process, fix, review... your final document.

> 2. Your are relaying in something that is not in the spec and even unified in GitHub, so maybe tomorrow change as you have a bunch of documents broken, like happened a few months ago with #Foo over # Foo.

This is not true.  Paragraphs in Markdown are very well described in the specs, and were specifically designed to support this, as nearly all professional typesetting systems from troff to TeX and other formats like HTML; examples of markdown specs explicitly explaining this:

- https://daringfireball.net/projects/markdown/syntax#p
- http://spec.commonmark.org/0.5/#paragraphs

> 3. Adds another thing to worry to make a PR, also adds more work to do from the PR reviewers, and the worth a back and forth about if the line is too long or not.

This is just the first comment again and it is misleading.  The whole point of it is to make it easier to iterate over versions until your final document is ready, as Kernighan explained in 1974.

**Comment by mcuadros** [comment]
GitHub, has his own flavored implementation, were they have his own specs, that as you proveed in the third message are not very well unified. 

I don't see any mayor improvements using this method, maybe  back in 1974 was useful, but today with GitHub, I can see perfectly the changes on a paragraph. 

![screenshot_2017-06-14_13-24-10](https://user-images.githubusercontent.com/1573114/27130063-e5375c5c-5104-11e7-98f8-53d2d0d0c128.png)
https://github.com/src-d/guide/pull/7/files?diff=unified

As the third point is the most important, you can see here a sneak peek of the amount of time we are loosing, dealing with small things. 

So at this time I am acting as `benevolent dictator` and rejecting this proposal.

**Comment by smola** [comment]
I think the most important thing here is agreeing on a way of doing it for everyone, whether it's semantic line-feeds, fixed-with or even single line per paragraph. We could then discuss if we want to make it easier to follow (e.g. adding modelines and/or `.editorrc` to the repo) and if we want to enforce it (e.g. adding checks on Travis).

I really don't have a strong opinion on what to choose though, so for me it looks like [bikeshedding](http://bikeshed.org/) all over the place :wink:
