### ISSUE TITLE
Explicitly state the PR merge rules

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/guide#41]
@mcuadros <s>I definitely saw the rules you wrote to merge PRs somewhere. We need to put them here. E.g.

private projects - 2 people must approve
public projects - 3 people and Maximo
...
</s>

Besides, it would be awesome to list the owners of each project who can merge PRs backing Maximo. E.g. myself in src-d/blog, etc.

Besides, there is an exclusion with ML projects since only me and @EgorBu are able to understand what's going on.

**Comment by alcortesm** [comment]
@vadim I think they are here: https://github.com/src-d/workflow/blob/master/dev-team/git-workflow.md

**Comment by vmarkovtsev** [comment]
Thanks Alberto! Removed the first part.

**Comment by vmarkovtsev** [comment]
Wait a minute... Why is it private?

**Comment by alcortesm** [comment]
I'm sorry @vadim, I don't know.

**Comment by mcuadros** [comment]
@vmarkovtsev bring this topic to the next retrospective meeting.
