### ISSUE TITLE
Scaling issues with the code review policy for public repos

### ISSUE THREAD

**Issue by alcortesm** [src-d/guide#50]
The current code review policy is that PR made to public repos must be reviewed by Máximo and another person: https://github.com/src-d/guide/blame/master/engineering/git-flow.md#L23

But I think that is not going to scale well now that we are publishing so many repos.

I don't know what was the original intention behind this rule, so I cannot propose alternatives that preserve it.

**Comment by mcuadros** [comment]
This is the first point of the today's meeting:
https://gist.github.com/mcuadros/354a45940f9be6e84490a4c28458ad02
