### ISSUE TITLE
Vacation carryover policy limited to 23 days on KinHR

### ISSUE THREAD

**Issue by marnovo** [src-d/guide#57]
Was checking with KinHR support and it seems we currently have a maximum 23 days carryover policy set there, which conflicts with:

> Finally, if you don't use all your days in one year, any unused days will carry over to the next.

_From : https://github.com/src-d/guide/blob/master/talent/flexible_holidays_working_schedule_remote_work.md_

Their customer support answer on how to fix it:

> If you wanted to have an unlimited amount of carryover, you can set the maximum to a very high number (say 100 days).  Then, in this scenario, you would be able to carry over 35 days (35 + 23).

**Comment by jorgeschnura** [comment]
@estherrgarcia please fix it

**Comment by estherrgarcia** [comment]
Done

**Comment by marnovo** [comment]
Perfect, thank you! Closing this.
