### ISSUE TITLE
[git-flow.md] Code review and requested changes

### ISSUE THREAD

**Issue by EgorBu** [src-d/guide#59]
Proposal for improvement:
I think it will be really useful if we will have some integration with slack to make a notification about pending reviews.
Right now it's pretty easy to miss mail from GitHub.

**Comment by Serabe** [comment]
![2017-08-07 at 10 59](https://user-images.githubusercontent.com/36221/29019638-728e820e-7b5f-11e7-8081-24c468d222de.png)

That blue dot means you have pending notifications. I review from there. Much simpler than email if you receive a lot of them.

Also, if you haven't done so yet, you can add several emails to your profile and select to which account GitHub will send the notifications for a particular org.

**Comment by jorgeschnura** [comment]
@mcuadros any way to add that bot to Slack?

**Comment by mcuadros** [comment]
This is a nightmare and also is doesn't add value to the remote comunity, since this notification is private for the user.

**Comment by jorgeschnura** [comment]
Can we close the issue then?

**Comment by campoy** [comment]
+1 on closing the issue, GitHub notifications is enough IMHO
