### ISSUE TITLE
Analyze, adapt and implement management tools we're missing

### ISSUE THREAD

**Issue by marnovo** [src-d/guide#60]
Would love to see some of these adapted to source{d} and implemented (I can help):

> # [Google is sharing its management tools with the world](https://qz.com/1058563/these-are-googles-tools-for-effective-management/)
>
> Speaking at his alma mater in January, Sundar Pichai, Google’s low-profile CEO, revealed his key to effective management: “Let others succeed.”
>
> Enacting Pichai’s advice is easier said than done. But Google is sharing some tools that might help. Its Re:Work blog is offering a series of instructive documents used by managers at Google. They cover everything from feedback and career development to setting agendas for one-on-ones, and codify the insights Google gleaned from spending years analyzing reviews and other observable data at the company to determine essential leadership traits.
>
> Here’s an overview of what’s available. Each section header below has the link to the corresponding documentation from Google.
>
> ## [Manager feedback survey](https://rework.withgoogle.com/guides/managers-give-feedback-to-managers/steps/try-googles-manager-feedback-survey/)
> 
> Googlers evaluate their managers on a semi-annual basis with a 13-question survey. The first 11 measure whether employees agree or disagree with statements like “My manager shows consideration for me as a person.” The final two questions (“What would you recommend your manager keep doing?” and “What would you have your manager change?”) are open-ended.
>
> At Google, these survey responses are reported confidentially, and managers receive a report of anonymized, aggregated feedback, plus verbatim answers to the two open-ended questions. “The feedback a manager gets through this survey is purely developmental,” Google says. “It isn’t directly considered in performance or compensation reviews, in the hope that Googlers will be honest and constructive with their feedback.”
> ## [Career conversations worksheet](https://rework.withgoogle.com/guides/managers-care-professionally-personally-for-team/steps/structure-career-conversations-with-grow/)
> 
> Google’s management analysis reveals that above all, employees value knowing that their manager is invested in their personal success and career development. To help managers effectively discuss development with their direct reports, Google uses the GROW model—which organizes the conversation into four recommended sections:
>
> - Goal: What do you want? Establish what the team member really wants to achieve with their career.
> - Reality: What’s happening now? Establish the team member’s understanding of their current role and skills.
> - Options: What could you do? Generate multiple options for closing the gap from goal to reality.
> Will: What will you do? Identify achievable steps to move from reality to goal.
> ## [“One Simple Thing” worksheet](https://rework.withgoogle.com/guides/managers-care-professionally-personally-for-team/steps/use-one-simple-thing-for-goal-setting/)
> 
> To encourage personal well-being and work-life balance, Google uses the popular goal-setting practice “One Simple Thing.” The goal should be specific enough to measure its impact on one’s well-being. “Managers can encourage team members to explain how pursuing this one thing won’t negatively affect their work,” Google explains. “That goal then becomes part of a team member’s set of goals that managers should hold them accountable for, along with whatever work-related goals they already have.”
>
> Some examples of “One Simple Thing” goals include “I will take a one hour break three times a week to work out,” and “I will not read emails on the weekends.”
>
> ## [1:1 Meeting agenda template](https://rework.withgoogle.com/guides/managers-coach-managers-to-coach/steps/hold-effective-1-1-meetings/)
> 
> At Google, the highest-rated managers hold frequent one-on-one meetings with their direct reports. However, as most leaders know, individual check-ins can [often feel rushed and disorganized](https://hbr.org/2016/08/how-to-make-your-one-on-ones-with-employees-more-productive). To squeeze the most out of each one-on-one (which Google managers are advised to hold every week or two) Googlers set up a shared meeting agenda ahead of time—which both the manager and the report should contribute to.
>
> Some agenda items Google suggests include:
> - Check-in and catch-up questions: “What can I help you with?” and “What have you been up to?”
> - Roadblocks or issues
> - Goal updates
> - Administrative topics (e.g., upcoming vacations, expense reports)
> - Next steps to confirm actions and agreements
> - Career development and coaching
>
> ## [New manager training course materials](https://rework.withgoogle.com/guides/managers-develop-and-support-managers/steps/review-googles-new-manager-training/)
> 
> As Google explains, “These course materials were originally designed for Google managers to help them transition from individual contributor roles to manager roles.” As anyone who has done this can attest, conducting the transition gracefully requires a bit of perspective shifting, and more than a little awareness building.
>
> The course materials include a [facilitator guide](https://docs.google.com/document/d/16aDChcr2W6r683bCUeOD-4FEP3sx754_n37-bSHPFw4/edit) (to help whoever is training the new managers), a new manager [student workbook](https://docs.google.com/presentation/d/1U4OUc2OHJ_x-rYz-Ue5yiLx7u-CatxwyKw-eud0KukQ/edit) (including interactive exercises), and the [presentation slides](https://docs.google.com/presentation/d/13-rj7ZqlyuHNli9Ybd5D8g-qqUNtG81t3JLq7JV5c2o/edit) that Google trainers use internally.

**Comment by eiso** [comment]
I am closing this for now, because it's very broad. However I think there are some nice goodies in here. @marnovo since you just spent the management days and OKR day with us. Can you please make a proposal (in separate issues) of some you think will benefit the team? (The one we don't have and I really like is the manager survey)
