### ISSUE TITLE
Describe teams and process

### ISSUE THREAD

**Issue by smacker** [src-d/guide#72]
For an outside person it's not very clear what Data Intelligence, Machine Learning and Applications teams are doing and how they communicate with each other. (for other teams it's more or less clear because of the name, but not how they are connected)
In my opinion it's worth to explain the process of development here. Some graph like this:

```
Data Retrieval => Language Analysis => Machine Learning 
                                                        =>  Applications => Infrastructure
                          Product
```

And some description like:

Data Retrieval - retrieve and store source code from one project to all of the world's public code. Build such projects as go-git, rovers, borges, siva
Language Analysis - language detection on a large scale and build querying, features extraction, collects statistics for any programming language that enables code analysis for all open source code and enterprise. Build such projects as envy, babelfish
...
Applications - applies whole stack and expertise to solve real word problems as code duplication, smart diffs, search for repositories, projects evolving reports
Infrastructure - runs kubernetes cluster on bare metal and AWS to allow process millions of code lines every minute

P.S. Anything above can be incorrect and just my fantasy, because I don't really know how everything works yet.

**Comment by eiso** [comment]
This is a really good idea, sorry I haven't commented before. Let's do this. @mcuadros or @campoy either of would you like to take ownership here to adding this.

**Comment by campoy** [comment]
I don't think I have the knowledge on process yet in order to write this document.
But it would be a very useful resource specially as we write the "Engineering Culture at source{d}" document.

**Comment by eiso** [comment]
@tsolakoua we can now extract this information from our job positions posts. I am assigning this to you. It's a low/medium priority item.

**Comment by tsolakoua** [comment]
Work at https://github.com/src-d/guide/pull/161
