### ISSUE TITLE
National holiday policy for remote workers

### ISSUE THREAD

**Issue by marnovo** [src-d/guide#78]
Given that KINHR tracks holidays that are in the Madrid office, what is the policy for people working remotely and subject to different national holidays (and the alike)?

P.s.: for example, the workaround so far with Ricardo, is: he schedules on KINHR asking for holidays on the days of Portuguese national holidays, and whenever he works regularly in a day that's a national holiday in Madrid he gets a +1 day. It makes the math check out and give transparency to it.

**Comment by eiso** [comment]
I think this is a good solution. Could you add it in a PR to the guide's holiday policy.

**Comment by eiso** [comment]
PR has been merged for this as far as I know.
