### ISSUE TITLE
A place for meta-discussions

### ISSUE THREAD

**Issue by bzz** [src-d/guide#82]
It would be really great to have a recognized communication medium at source{d}, where everyone could engage in meaningful discuss on meta-topics. With some arguments, threads, links to each message and some time to think and an opportunity for everyone, even the least loudest persons, to express their opinions on important subjects. 

Fiding such communication medium is VERY hard thing, both technically and culturally.. and Slack/IM does not address it (and has [it's own issues](http://jshakespeare.com/how-slack-hooks-users-through-artificial-urgency) as main communication tool). 

Coming from open source community background, this means finding an equivalent of Mailing List archive. 

ML archive itself is sub-optimal in many ways (using only emails as transport), but it is:
- async
- threaded
- searchable
- has calendar navigation
- each thread has permanent URL, that’s easy to get back to, share, link in sub-sequent discussion, etc

I know that email is un-popular choice at source{d}, but I really wish we find something that works for us… so why do not we try **this repository's issue**?

This is especially critical, as source{d} faces a challenge to become a remote-first company - otherwise, you know, "all these moments will be lost in time, like tears in the rain". 

There is already some good start like #72 and #81 - let's see how that goes.

What do you guys think? Is that actually a pain-point for anybody else? If so, do you think suggested solution might work? Looking forward your opinions!

**Comment by eiso** [comment]
I fully support this, by keeping the issues in this repo, we could make following up (often by management) accountable at company wide meetings every two weeks.

**Comment by abeaumont** [comment]
I'm quite in favor of MLs tbh.

**Comment by juanjux** [comment]
Alternatively we could use some forum software with support for threading.

**Comment by vmarkovtsev** [comment]
I encourage the emails ban. It is complete hell in big companies and every time I received a `Re: RE: RE: Re: 댓글: Re: Fwd: Re: Question` I wanted to break my keyboard.

**Comment by mcuadros** [comment]
I was speaking with Alex (sorry was in the kitchen), I maybe the best way is using PR, is the best tool since you have have threads, linkable comments, etc. And we are very use to it.

The place to do it, could be the "interview" repository renamed to "company". So there we kind discuss any proporsal.

**Comment by juanjux** [comment]
That could do, yes.

**Comment by ajnavarro** [comment]
Having PRs or issues we can have the two worlds (MLs one and only repository one). You will able to answer directly using the email if you are subscribed to that PR or issue, obviously receive emails too, all grouped by issue or PR. So I'm in on the PR implementation of this idea.

**Comment by jfontan** [comment]
The good thing about using PRs is that we are not adding a new source of information or learning a new tool. It's the same thing we use for other tasks.

There's also the team discussions feature added by github. I haven't checked it nor I am a fan of forums.

https://help.github.com/articles/about-team-discussions/

**Comment by marnovo** [comment]
My views on specific topics that were mentioned here:

## Need of a slower-paced meta-discussion channel

- I am supportive of the idea as I believe we often need to bring some things to the table but often feel there's not really a place for that—particularly in more thoughtful discussions, when the "fast line" channel of Slack just pushes and drowns things even with threading, so you tend to rely on reminders and memory to keep to discussions before they go away.
- The `src-d/guide` has worked well to a certain extent for this purpose, although I wonder why to many of us it hasn't felt like the obvious channel to have this kind of discussion. Could it be privacy concerns, lack of purpose clarity, relating it to more external-facing and/or administrative issue?

## Views on options for that channel

### 1. An specific #meta Slack channel or so
- Experience/interface is mostly consistent throughout OSes, clients.
- Everyone is very aware of it and usually online on Slack.
- Everyone is very familiar with its usage, features, etiquette.
- Search is quite powerful, but not easy to navigate and sort.
- Poor threading and average quoting, makes it hard to notice threads and follow up later.
- File/attachment management is average.
- Messages can be edited for a while or deleted at any point.
- Obscure message pinning, basically you pin once and no one ever finds the pinned topics again besides by eventual chance. 
- Fast-lane flooding, usually not very async friendly unless very structured (e.g.: only allow threading).
- Notifications can be annoying but hard to ignore. Good granularity between "something was said" vs. "I was mentioned".
- Not very clear when a conversation is "done" or "solved" without the help of other tools.
- Needs some work with the API to migrate to a new service, but seems mostly ok.
- Privacy/security is ok, it is clear that only org members can access and read it.
- **Conclusion**: would need some rules and thought on how to serve the intended usage, good notifications and search, but still feels a tad unnatural and adapted, seems like could break in the long term.

### 2. Email/mailing lists as a team discussion channel:
- Experience/interface is quite consistent throughout OSes, clients, depends on client features.
- Everyone is very aware of it and I guess check at least some times a day.
- Everyone is very familiar with its usage, but not so much with features, and likely not etiquette.
- Search is quite powerful and rather easy to navigate, when things are properly organized, labeled.
- You need to rely on people to make things the very right way or it all falls apart (threading, grouping, labeling, correct recipients).
- Thread/message pinning depends on each individual.
- File/attachment management is average.
- You cannot edit or review things, usually meaning breaking things in the examples above. Messages cannot be edited once sent+received, nor erased.
- You cannot cross reference emails (in theory you could by attaching mail files, which was Outlook hell).
- Mixes way too many topics between internal/external users, site updates, etc. You have to rely on everyone to be super organized not to miss things yet not stay half a day reading email.
- Notifications can be annoying but hard to ignore, until you really get flooded and start ignoring things. Poor granularity between "something was said" vs. "I was mentioned", would need to rely on to:/cc: filters and proper usage.
- Not very clear when a conversation is "done" or "solved" without the help of other tools.
- Needs a lot of work depending on how structured/organized things were to migrate to a new service, although some ML management tool could help on that.
- Privacy/security is meh, although can be encrypted it is easy to mistakingly cc a wrong/external email, very easy to fwd things outside, so feel a tad less private.
- **Conclusion**:  not worth the trouble teaching and enforcing a ton of rules that break very easily and don't have all the features we need. Search and file management is good. Very easy to miss things or drown in messages. Plus, I wonder how many people at the company check their email frequently…

### 3. GitHub issues

- Everyone is very aware of it and I guess check at least some times a day.
- Everyone is very familiar with its usage, features, etiquette.
- Search is just ok, at maximum as good as the other options.
- Fairly low setup/cognitive overhead cost, maybe some general guidelines and labels at most. Can be edited easily. People can break things and still be easily maintainable.
- Threading is just ok, relies some work using markdown formatting for quotes/quotes of quotes, can cross-reference issues.
- File/attachment management is poor, a least without extensions/integrations.
- Messages and threads can be edited and besides parent ones can be deleted.
- You can cross-reference conversations easily, particularly using soft links (hard links could break with repo renaming).
- Topics can be sandboxed by using different repos or by using labels, which apply across all users.
- Notifications aren't very noticeable, you need to proactively look for GitHub notification page or issue mentions. Maybe necessary a reminder on Slack on some integration. One "extra" option though is to get notifications via email: works quite well, but may flood your email when subscribed to many repos/threads. Good granularity on new message vs mention.
- Much clearer when a conversation is "done" or "solved".
- Needs some work with the API to migrate to a new service, but seems mostly ok.
- Privacy/security is ok, but might not be very clear when a subject is sensitive and should not be discussed in public in the case of `guide` repo.
- **Conclusion**: it's the one that solves most of the problem without creating a lot of new cognitive overhead and fairly maintainable in the LT. The weakest points are poorer search and file management, and the less intrusive notifications can work both ways (although email can be used here). Important to discuss the pros/cons of using a public vs private repo.

### 4. GitHub PRs

- Many points in common with GitHub issues above, will focus on the differences.
- Need commits to prompt a PR, although can more easily consolidate feedback into a single, versionable, locally storable and offline accessible document.
- Search and threading can be tricky as conversations happen along reviews/comments, specially when new commits happen and the interface folds pre-commit comments.
- Mixes Git and GitHub features, not very clear how these relate through the API in case we need to migrate, for example
- **Conclusion**: very similar to issues on a repo, but tends to have more cons than pros vs issues.

### 5. Actual forum tool

- Needs people to check this new tool regularly, can be alleviated with some slack integrations/reminders.
- Most people are mostly familiar with its usage, features, etiquette as it resembles often GitHub's.
- Search is usually good or very good.
- Quite high setup and cognitive overhead, after initial setup and guidelines not so much.
- Threading is usually good, although in long conversations can be overdone.
- File/attachment management is usually ok to good.
- Threads and messages can be edited/deleted or not, depending on settings.
- You can cross-reference threads/messages.
- Topics can be sandboxed with tags and subforums.
- Notifications are usually poor, as usually it's only by visiting the notifications area or by activating email (which has all the benefits/issues discussed in other options). Not every system has distinction between mention and new messages.
- Much clearer when a conversation is "done" or "solved".
- Needs some work with to migrate to a new service, but usually fairly easy.
- Privacy/security is ok.
- **Conclusion**: has its set of similarities to GitHub and to email. As the names implied, often tools meant for this very purpose. The weakest spots are setup + overhead, poor notifications, likely no integration with other ecosystems (GitHub).

## Partial conclusion

My partial conclusion from the above comparison is that **GitHub issues in a repo** are likely the best solution, with low setup+overhead, flexible and maintainable, and fair forum features. As long as we set some guidelines (guide or not, private or not, etc.) and maybe set up a weekly reminder on #general Slack so people revisit it, we should be good to go.

**Comment by mcuadros** [comment]
Please take a look to https://github.com/src-d/company
And contribute with all the documents are in Google Driver, to have all in the same please, as well do any PR and issue to suggest changes or improvements.
