### ISSUE TITLE
write hiring section 

### ISSUE THREAD

**Issue by campoy** [src-d/guide#83]
It should describe our process, how to apply, and how to refer candidates.

**Comment by bzz** [comment]
And this can be a good place to link it from https://github.com/src-d/guide/blame/master/README.md#L26

**Comment by tsolakoua** [comment]
How developers can apply and the hiring process in the PR here: https://github.com/src-d/guide/pull/95

**Comment by eiso** [comment]
Closing this issue since it's already in PR stage and will soon be merged.
