### ISSUE TITLE
Define a project skeleton

### ISSUE THREAD

**Issue by dpordomingo** [src-d/guide#93]
Since we're trying to improve the way our users/developers/visitors approach our projects, I think it could be a good idea to propose a project skeleton to be followed.

Benefits of having a common skeleton already pre-defined:
- it makes our projects more homogeneous, what lets everyone to know what to expect where,
- it would let us start a project with all our agreed requirements ready to be fulfilled,
- it could be also used in "starter apps" (like [src-d/platform-starter](https://github.com/src-d/platform-starter))

Context:
I imported this idea from [documentation at source{d} #84](https://github.com/src-d/guide/pull/84)

In my opinion, the following could work:
```
project-skeleton/
├── .github
│   ├── CODE_OF_CONDUCT.md
│   ├── CODEOWNERS
│   ├── CONTRIBUTING.tpl.md
│   ├── ISSUE_TEMPLATE
│   └── PULL_REQUEST_TEMPLATE
├── DCO
├── LICENSE.apache
├── LICENSE.gpl
└── README.tmpl.md
```
And I'd put that directory under [guide/engineering/](https://github.com/src-d/guide/tree/HEAD/engineering)

**Comment by campoy** [comment]
I somehow can't assign this issue to myself.
Can I haz the rights, @mcuadros ?

**Comment by eiso** [comment]
I happen to come across this, will give you the rights.

**Comment by campoy** [comment]
Thanks, @eiso

**Comment by smola** [comment]
I think this is close to a project skeleton: https://github.com/src-d/guide/tree/master/engineering/documents

It would need to add some missing files, move some others, etc.

**Comment by smola** [comment]
@campoy I don't think so. But you can setup your local git `init.templatedir` to point there so that it is used by `git init`. See this: https://git-template.readthedocs.io/en/latest/

**Comment by campoy** [comment]
Ok, I do agree that that folder seems like a good candidate to be considered as the starting point for any repo.

Would you @smola like to update the engineering documentation to point to this directory?

Thanks

**Comment by smola** [comment]
@campoy Yes, I'll update docs and restructure the directory a little bit.
