### ISSUE TITLE
Suggestions for onboarding process

### ISSUE THREAD

**Issue by carlosms** [src-d/guide#94]
As a new hire myself, here are my thoughts on what can be helpful for the first few days:

1) Have a standard template for the onboarding issue checklist. For example, there is nothing terribly wrong with my issue (https://github.com/src-d/office/issues/22), but if it was a template in a repo I would open issues to
    - List all the mailing lists that I will be added to, and the purpose for each one
    - Add the welcome talks

2) Have a template for a welcome email. I think a short email can be a nice and simple point of entry to refer at a later date.
Something along the lines of:

> Welcome to source{d}. Here are few first steps to get you going:
> 
> - Read the [guide](https://github.com/src-d/guide).
> - This is your personal onboarding issue (link). Fell free to reach the person responsible for each item.
> - In the Applications/Infrastructure/... team we use these tools: (list of tools and what they do. e.g. github project board, Geekbot, etc)
> - We have a lot of repositories, but for now you should focus on getting familiar with the contents of (list of relevant repos for your team/role).
> - Consider turning on github notifications at least for (list of repos)

**Comment by eiso** [comment]
This is an awesome idea! @tsolakoua do you want to take care of this? Also coordinate with @estherrgarcia once she is back since she has some awesome onboarding/email material

**Comment by tsolakoua** [comment]
Yes, @eiso sure! Will start working on it asap and finalise it when Esther comes back.

**Comment by eiso** [comment]
@carlosms just so you're aware, this is being followed-up on: https://github.com/src-d/minutes/pull/119

**Comment by bzz** [comment]
Really nice suggestion, aligned with discussion on https://github.com/src-d/minutes/pull/146#discussion_r170191543

@tsolakoua please, let me know if you need help converting this to an [issue template](https://github.com/blog/2495-multiple-issue-and-pull-request-templates)

**Comment by dennwc** [comment]
Note that notifications for repositories are enabled automatically when joining the team on GitHub (including guide, minutes, etc).

**Comment by tsolakoua** [comment]
@r0mainK and @fulaphex Is there anything you would like to mention for your onboarding process? We already describe the [on-boarding process](https://github.com/src-d/guide/tree/master/talent/onboarding) and I am also preparing a welcome email for new members. Feel free to write here your feedback and make any suggestions. 
I am asking you two because you joined source{d} since we posted the onboarding documents in our guide.

**Comment by eiso** [comment]
After speaking with @tsolakoua today, she gathered everyone's feedback and is continuously improving the process. I am therefore closing this issue for now.
