### ISSUE TITLE
Define get-together requirements/limitations so it could be proposed by anyone 

### ISSUE THREAD

**Issue by dpordomingo** [src-d/guide#98]
If we could know about the [get together](https://github.com/src-d/guide/blob/184fb8937a293365f4e8a97b439705c898508d9d/office/company_events.md#get-togethers) requirements and limitations, we could propose events on our own.

To do so, I think we should know, at least:
- budget,
- the minimum amount of people needed,
- the days when it can occur,
- when can we leave the office and when should it finish,
- if is there any limitation/expectation on the time duration,
- if there is a distance limit (regardless the one limited by the budget, time limits and 
 duration),
- if the `+1 invitation` should be always an option, or it depends on the activity,
- if the activity must include drinks and/or food,
- the process to be approved,

and any other I could miss

**Comment by eiso** [comment]
I am assigning this to @estherrgarcia now she's back from her holidays. @estherrgarcia get together's are owned by you, so let's make a pull request to the guide.

**Comment by eiso** [comment]
@estherrgarcia just pinging you, in case you missed this. Let me know any input you need from me.
