### ISSUE TITLE
Clarify index/content of this repo, and assign owners

### ISSUE THREAD

**Issue by dpordomingo** [src-d/guide#99]
The [main readme](https://github.com/src-d/guide/blob/master/README.md) contains a huge table of contents that is easily outdated when it appears new content.

What if each section would contain its own `README.md` instead of maintaining a general one?
That way, each section could have its own description, index and even more: its own  [owner](https://github.com/blog/2392-introducing-code-owners) ("maintainer"),

for example: `.github/CODEOWNERS` could be:
```
# default
* @jorgeschnura 

# sections
developer-community/* @campoy 
engineering/* @mcuadros 
general/* @jorgeschnura 
office/* @estherrgarcia 
talent/* @tsolakoua
product/* @marnovo
```

**Comment by eiso** [comment]
I think this is a great idea. Sorry for taking so long to respond to this (which kind of proves your point of section owners). 

I'll make a PR for this today, to kick off this process.
